/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-11-01 04:16:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.io.IOException;

public final class Post_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>게시판 글쓰기 - 결과화면</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>글쓰기</h2>\r\n");
      out.write("\t");
 
	request.setCharacterEncoding("euc-kr");
	String name = request.getParameter("NAME");
	String num1 = request.getParameter("NUMBER");
	String num2 = request.getParameter("NUMBER2");
	String id = request.getParameter("ID");
	String secret = request.getParameter("SECRET");
	String secretcur = request.getParameter("SECRETCUR");
	String email = request.getParameter("EMAIL");
	String domain = request.getParameter("DOMAIN");
	String first = request.getParameter("FIRST");
	String second = request.getParameter("SECOND");
	String trird = request.getParameter("TRIRD");
	String job = request.getParameter("JOB");
	String yn = request.getParameter("YESORNO");
	String hobby = request.getParameter("HOBBY");
	
	int int_num1= Integer.parseInt(num1);
	int int_num2= Integer.parseInt(num2);
	int Pfirst=Integer.parseInt(first);
	int Psecond=Integer.parseInt(second);
	int Ptrird=Integer.parseInt(trird);
	int yns= Integer.parseInt(yn);
	if (yns==1)
		yn="수신";
	else
		yn="거부";
	
	String result;
	if(secret.equals(secretcur)){
		PrintWriter writer = null;
		try{
			String filePath = application.getRealPath("/start2/result.txt");
			writer.printf("이름: %s \n", name);
			writer.printf("주민등록번호: %d-%d\n", int_num1,int_num2);
			writer.printf("아이디: %s\n", id);
			writer.printf("비밀번호: %s\n", secret);
			writer.printf("이메일: %s@%s\n", email,domain);
			writer.printf("핸드폰번호: %d-%d-%d\n", Pfirst,Psecond,Ptrird);
			writer.printf("직업: %s", job);
			writer.printf("수신여부: %s", yn);
			writer.printf("관심분야: %s", hobby);
			result = "SUCCESS";
		}
		catch (Exception ioe) {
			//result = "SUCCESS";
			result = "FAIL";
		}
		finally{
			try{
				writer.close();
			}
			catch (Exception e){
			}
		}
	}
	else{
		result = "FAIL";
	}
	response.sendRedirect("result.jsp?RESULT="+result);
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
