/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-12-04 02:02:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewLineMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tags/newLine.tag", Long.valueOf(1512352880000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>오늘의 메뉴</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_util_005fnewLine_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t저녁 메뉴<br>\r\n");
      out.write("\t");
      if (_jspx_meth_util_005fnewLine_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t불고기 덮밥<br>\r\n");
      out.write("\t카레라이스<br>\r\n");
      out.write("\t쫄면<br>\r\n");
      out.write("\t");
      if (_jspx_meth_util_005fnewLine_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_util_005fnewLine_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  util:newLine
    org.apache.jsp.tag.web.newLine_tag _jspx_th_util_005fnewLine_005f0 = new org.apache.jsp.tag.web.newLine_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_util_005fnewLine_005f0);
    try {
      _jspx_th_util_005fnewLine_005f0.setJspContext(_jspx_page_context);
      // /NewLineMenu.jsp(11,1) name = color type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_util_005fnewLine_005f0.setColor("blue");
      // /NewLineMenu.jsp(11,1) name = size type = java.lang.Integer reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_util_005fnewLine_005f0.setSize(new java.lang.Integer(25));
      _jspx_th_util_005fnewLine_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_util_005fnewLine_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_util_005fnewLine_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  util:newLine
    org.apache.jsp.tag.web.newLine_tag _jspx_th_util_005fnewLine_005f1 = new org.apache.jsp.tag.web.newLine_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_util_005fnewLine_005f1);
    try {
      _jspx_th_util_005fnewLine_005f1.setJspContext(_jspx_page_context);
      // /NewLineMenu.jsp(13,1) name = color type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_util_005fnewLine_005f1.setColor("red");
      // /NewLineMenu.jsp(13,1) name = size type = java.lang.Integer reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_util_005fnewLine_005f1.setSize(new java.lang.Integer(20));
      _jspx_th_util_005fnewLine_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_util_005fnewLine_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_util_005fnewLine_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  util:newLine
    org.apache.jsp.tag.web.newLine_tag _jspx_th_util_005fnewLine_005f2 = new org.apache.jsp.tag.web.newLine_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_util_005fnewLine_005f2);
    try {
      _jspx_th_util_005fnewLine_005f2.setJspContext(_jspx_page_context);
      // /NewLineMenu.jsp(17,1) name = color type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_util_005fnewLine_005f2.setColor("blue");
      // /NewLineMenu.jsp(17,1) name = size type = java.lang.Integer reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_util_005fnewLine_005f2.setSize(new java.lang.Integer(25));
      _jspx_th_util_005fnewLine_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_util_005fnewLine_005f2);
    }
    return false;
  }
}
